### PR TITLE
Add application_insights

### LINKED ISSUE #28: Request: Support application_insights
Support for azurerm_application_insights and azurerm_application_insights_web_test would be helpful. Thanks.

### PR DESCRIPTION
**Pull request by cdhunt**
Is this slug acceptable?

Fixes #28

### CODE REVIEW

**Comment by travisty-** [comment]
@cdhunt I would lean toward using `appi` as the slug to align with the recommended naming and tagging conventions.
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging

**Comment by cdhunt** [comment]
Thanks, @travisty-. Updated as suggested.

**Comment by Nepomuceno** [comment]
THe data it is generatef from the json file so the changes need to be made to the json file and auto generated for the other files

**Comment by cdhunt** [comment]
@Nepomuceno Which one(s)?

**Comment by Nepomuceno** [comment]
Terraform fmt needs to be run

you can run it using `terraform fmt` in your console

**Comment by cdhunt** [comment]
> Terraform fmt needs to be run
> 
> you can run it using `terraform fmt` in your console

I did, but before the `go run`. I don't have `make` so doing this all by hand.

**Pull request merged**
