### PR TITLE
random_string: Use numeric instead of the deprecated number

### PR DESCRIPTION
**Pull request by taoufik07**

### CODE REVIEW

**Comment by jomach** [comment]
Can we merge this ?

**Comment by iwalt** [comment]
Should the required version of `hashicorp/random` be upgraded to at least 3.3.0 with these changes? Regardless, it would be lovely not to see the deprecation warnings anymore. Thanks!

**Comment by Nepomuceno** [comment]
When you change this you need to change in the template not in the generated file. Will fix this together with some changes that I will be merging today.

**Comment by Nepomuceno** [comment]
Thank you for the contribution and to point this out.

**Pull request closed without merging**
