### PR TITLE
Add Load Test support

### PR DESCRIPTION
**Pull request by LaurentLesle**
Add support for Load Testing name required by the AVM Load Test Module

image

Name cannot contain special characters \/""[]:|.<>+=;,?*@&, whitespace, 
    or begin with '_', '-' 
    or digits or end with '_' or '-'.
    The value must be between 1 and 64 characters long.

### CODE REVIEW

**Comment by segraef** [comment]
lgtm, let's wait for @Nepomuceno

**Comment by Nepomuceno** [comment]
You should run `make generate` to generate the other fiels before the commit it is accepted.

**Comment by LaurentLesle** [comment]
Ok let me have a look

**Comment by LaurentLesle** [comment]
@Nepomuceno Updated.

**Comment by Nepomuceno** [comment]
@LaurentLesle Merged :)

**Pull request merged**
