### PR TITLE
Windows VMSS resource name is 64 chars

### PR DESCRIPTION
**Pull request by nyanhp**
Updating the VM Scale Set code. While it is correct that the `host name` of the Windows VMs still seems to be limited to NETBIOS names with 15 characters, the `resource name` of the scale set itself is 64 characters as outlined here: <https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules>.

It might be worthwile to add an output like `scale_set_instance_prefix` or simply use the `virtual_machine` which is limited to 15 characters when generating the instance names.

### CODE REVIEW

**Comment by nyanhp** [comment]
@Nepomuceno that is the point if this PR, correct. Anyone currently trying to get a longer name than 15chars for a scale set resource is not able to. They, however, should be as the 15char limit is imposed on the hostname inside the VM, not on the resource.

Which change are you requesting in particular?

**Comment by Nepomuceno** [comment]
This resource needs to keep the minimum level of compatibility between linux and windows for anyone that wants to use the longer name can use [azurerm_linux_virtual_machine_scale_set](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine_scale_set)
This iss also the recomended way to provision Linux vms. Would be ok for this change to change that resource.

**Comment by nyanhp** [comment]
Sorry, I still don't get what you want me to change. Is the requested change to close this pr? Then by all means, go ahead. I still don't get why one would limit **Resource** names not according to the limits of the platform (<https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules>) but to the ancient **NETBIOS** limit for the Windows OS.

**Comment by Nepomuceno** [comment]
The main thing it is that this would break the backwards compatibility changing this would break currently deployed resources this on top of the fact that if people used this for name itself it could fail.

Thx for the contribution and understanding.

**Pull request closed without merging**
