### PR TITLE
Hyphen allowed in des and dsk

### PR DESCRIPTION
**Pull request by ArgonQQ**
It is possible and for our case needed to enable dashes for des & dsk's. Is it possible to enable this and therefore fit to the official naming "limits"? If not can you please elaborate why this has been turned off? 

image

```
The value must have a length of at most 80.
The name must begin with a letter or number, end with a letter, number or underscore, and may contain only letters, numbers, underscores, periods, or hyphens.
```

Thanks for your feedback.

Best Regards,
Marcel

### CODE REVIEW

**Comment by Nepomuceno** [comment]
Hi @ArgonQQ When we create modules we don't change the terraform file directly we do change the json file that generate the resources. You can find this json file called resourceDefinition.json after you changed that file you can run `go run main.go` or `make build` this will auto generate the other files.

**Comment by ArgonQQ** [comment]
Hi @Nepomuceno , 

thanks for explanation. PR has been reworked.

**Comment by Nepomuceno** [comment]
Almost there now @ArgonQQ  After you change the json file you need to run make build or go run main.go to generate the tf file.

Thank you for the contribution.

**Comment by ArgonQQ** [comment]
Unfortunately, it now looks like PR has broken the pipeline. Is there a more detailed view of it?

**Comment by Nepomuceno** [comment]
The problem it is with the terraform formatting you can run `terraform fmt` to fix it.

You can check the result here https://github.com/Azure/terraform-azurerm-naming/pull/20/checks?check_run_id=844324431

**Comment by Nepomuceno** [comment]
👍 :shipit:

**Pull request merged**
